### ISSUE TITLE
It is a good MOD!

### ISSUE THREAD

**Issue by chenshi233** [Dacrenzio/GTFO-WeaponStatShower#1]
I like this MOD and I want it can be more useful in China,so I hope it can have a Chinese one of this MOD.I have try to do something to translate the MOD,but I have no kownledge about this,so I just can do some translate for you:
SEMI-A is 半自动
FULL-A is 全自动
BUST is 连发
ROF is 射速
SHORT CHARGE-UP is 短蓄力
LONG CHARGE-UP is 长蓄力
SMALL SPREAD is 扩散小
MEDIUM SPREAD is 扩散中
LARGE SPREAD is 扩散大
CHOCKED SPREAD is 收束扩散
DMG is 伤害
CLP is 弹容量
MAX is 总弹量
RLD is 换弹时间
PRCN is 精准倍率
DIST is 衰减距离
STGR is 硬直倍率
HIP is 后坐力
PIERC is 穿透
I haven't seen ADS yet,so I don't kown how to translate it
Thank you for your MOD again.
:D

**Comment by chenshi233** [comment]
STRK is 前锋
SHTR is 射手
SCOUT is 哨兵
I think ADS is 倍镜,maybe

**Comment by Dacrenzio** [comment]
Thank you for the comment and the compliments, I'll add the language option right after I come back from holidays :)

**Comment by chenshi233** [comment]
Thank you

**Comment by chenshi233** [comment]
I have forgot the melee weapons,I'll translate for it later.

**Comment by chenshi233** [comment]
HAMMER - BALANCED is 大锤 - 均衡
KNIFE - FAST is 刀 - 快速
BAT - FAST is 棍棒 - 快速
SPEAR - SLOW is 矛 - 慢速
SHORT RANGE is 短距离
MEDIUM RANGE is 中距离
LONG RANGE is 长距离
PIERCING is 穿刺
DMG.LGT is 轻击伤害
DMG.HVY is 重击伤害
RUN FALSE is 不能冲刺
STGR.LGT is 轻击硬直倍率
STGR.HVY is 重击硬直倍率
PRCN.HVY is 重击精准倍率
SLP.HVY is 重击沉睡倍率
ENV.LGT is 轻击环境倍率
ENV.HVY is 重击环境倍率
[C,B.H,O] is [胸，背，头，后脑]

**Comment by chenshi233** [comment]
If I forget something,you can remind me to supplement.

**Comment by Dacrenzio** [comment]
the only thing I ask is: can you please separate "STGR", "DMG" and "ENV" from ".LGT" and ".HVY"? thank you in advance :) I just need it just to be sure not to make mistakes

**Comment by chenshi233** [comment]
OK,I see...
STRG is 硬直倍率
DMG is 伤害
ENV is 环境倍率
SLP is 沉睡
.LGT is 轻击
.HVY is 重击

**Comment by chenshi233** [comment]
I think SLP translation is better for 沉睡倍率.

**Comment by Dacrenzio** [comment]
Thank you 👍 let's hope I can just slam the character in code and that I don't need to research all the ASCII codes

**Comment by chenshi233** [comment]
Thank you and good luck.

**Comment by Dacrenzio** [comment]
I was adding the language and I noticed something is missing:
- Deployable
- B-STRK (Big Striker)
- B-SHTR (big shooter)
- CHRG (chargers)
- C-SCOUT (charger scout)
- Shotgun-S (semi-automatic shotgun)
- Huge Spread (a single shotgun has this entry so easily missable)

**Comment by chenshi233** [comment]
Fine,I will use the localization translation of China players for some translations (the standard translation is in brackets).
Deployable is 可部署
B-STRK (Big Striker) is 大壮（大前锋）
B-SHTR (big shooter) is 大姐（大射手）
CHRG (chargers) is 黑刺（突袭者）
C-SCOUT (charger scout) is 黑触（突袭者侦察兵）
The standard translation of Shotgun-S (semi-automatic shotgun) is 半自动霰弹枪
And I'm not sure that the Huge Spread is something I think of.can you send a picture of Huge Spread?
If it's a weapon that can kill the Matrix with one shot,then its name is 三管霰弹枪.

**Comment by chenshi233** [comment]
Wait, wait, wait, wait,I was wrong
Huge Spread is 超大扩散

**Comment by Dacrenzio** [comment]
the spread is the size of the cone for shotguns, like how big is the cone and how much the shot spreads in it. so it just means that the pellet's spread for that shotgun is very big

**Comment by chenshi233** [comment]
I am so careless.

**Comment by chenshi233** [comment]
Sorry

**Comment by Dacrenzio** [comment]
Don't worry :) I appreciate the help 🔥

**Comment by Dacrenzio** [comment]
sorry I was wrong ahahaha, shoutgun-s is the firemode for the sentry shotgun, is the translation still ok? (shotgun-s stands for shotgun-sentry)

**Comment by chenshi233** [comment]
I see...It should be translated into 半自动霰弹射击

**Comment by chenshi233** [comment]
If there are no more questions, I will go to bed.
And I thank you on behalf of China players.
Good luck! Bro!

**Comment by Dacrenzio** [comment]
I developed an Alpha, try it out and tell me if everything is OK. after your OK I will publish this release

[Dacrenzio-WeaponStatShower-1.4.0.zip](https://github.com/Dacrenzio/GTFO-WeaponStatShower/files/12361103/Dacrenzio-WeaponStatShower-1.4.0.zip)

**Comment by chenshi233** [comment]
Sorry, I fell asleep when you sent me a message last night.

**Comment by chenshi233** [comment]
![image](https://github.com/Dacrenzio/GTFO-WeaponStatShower/assets/77187872/38e01c70-e19e-47c4-9eb6-69c420365497)
It doesn't seem to have changed.

**Comment by Dacrenzio** [comment]
You need to change the language in weaponStatShower.cfg
I don't know how to gain the language from the game's configurations

**Comment by chenshi233** [comment]
OH,I forgot to change the config file.

**Comment by chenshi233** [comment]
It seems that there are some mistakes in melee weapons.

**Comment by chenshi233** [comment]
Some translations are missing.

**Comment by chenshi233** [comment]
I'll tell you in detail what's wrong later.

**Comment by chenshi233** [comment]
I will also provide some translation optimization.

**Comment by chenshi233** [comment]
Thanks a lot!

**Comment by chenshi233** [comment]
MEDIUM SPREAD can change be 中度扩散，扩散中 looks like “the shotgun is spreading”

**Comment by chenshi233** [comment]
![image](https://github.com/Dacrenzio/GTFO-WeaponStatShower/assets/77187872/22cf17c5-bcb8-4cff-af49-35fe47ad591b)
there are two DMG,the second DMG should be STGR,the translate have no mistake.

**Comment by chenshi233** [comment]
![image](https://github.com/Dacrenzio/GTFO-WeaponStatShower/assets/77187872/c1f7075c-2a74-4991-b0de-0ad29ff058f1)
there are two DMG,too.But I forgot what was here.

**Comment by chenshi233** [comment]
"RUN FALSE"
"RUN" have be translated,but "FALSE" still is "FALSE"/laugh
In Chinese,"RUN FALSE" literally translates as “冲刺不能”,"不能冲刺" literally translates as “FALSE RUN” in English.:D
But you can't change the order of the two words.
I will try to come up with a more suitable translation to replace this one.

**Comment by chenshi233** [comment]
![image](https://github.com/Dacrenzio/GTFO-WeaponStatShower/assets/77187872/8b284aba-3361-46aa-a765-aa66cac70c08)
![image](https://github.com/Dacrenzio/GTFO-WeaponStatShower/assets/77187872/6f785cb5-d69e-49d4-a2e0-8c3873ed7067)
"ENV"'s translate is missing.

**Comment by chenshi233** [comment]
Maybe this is because the Chinese translation is too long.
I also will try to come up with a more suitable translation to replace this.

**Comment by chenshi233** [comment]
The SPEAR's second DMG was STGR.

**Comment by chenshi233** [comment]
Now there is only the translation problem of "ENV"

**Comment by chenshi233** [comment]
Now there is only the translation problem of "ENV" and “RUN FALSE”

**Comment by Dacrenzio** [comment]
going to check the values. the problem Is: I do a sum of the strings DMG and STGR with LGHT and HVY, so the translation is not as crisp as I want. the FALSE is added in code, it's just a printed boolean. I will problably just cancel the FALSE and add a text CAN'T RUN, 'cause I only show that info when you can't sprint

**Comment by chenshi233** [comment]
ah,I kown.
You just need translate the "RUN" into "不能",the "FALSE" translate into "冲刺"

**Comment by chenshi233** [comment]
This is a simple way.

**Comment by chenshi233** [comment]
This is a simple way.XD

**Comment by Dacrenzio** [comment]
the problem is: I just don't have the FALSE string in code 'cause it is generated on the fly, that's why for me is simplier to just say "can't run"

**Comment by chenshi233** [comment]
okey, there is just the "ENV" now,the poor guy

**Comment by chenshi233** [comment]
Do you have checked something mistake about the "ENV"?

**Comment by Dacrenzio** [comment]
yeah I forgot it in the JSON, alredy fixed it. But I need the translation for "can't run"

**Comment by chenshi233** [comment]
"can't run" translate into "不能冲刺".

**Comment by Dacrenzio** [comment]
[Dacrenzio-WeaponStatShower-1.4.0.zip](https://github.com/Dacrenzio/GTFO-WeaponStatShower/files/12368599/Dacrenzio-WeaponStatShower-1.4.0.zip)


Done :)

**Comment by chenshi233** [comment]
![image](https://github.com/Dacrenzio/GTFO-WeaponStatShower/assets/77187872/9170eed7-0a22-4e13-bad6-17a8658d83f3)
![image](https://github.com/Dacrenzio/GTFO-WeaponStatShower/assets/77187872/ec9e489c-2d73-4d0b-8429-5bb00e4692c3)
Yes,it is perfect MOD for Chinese player now.

**Comment by chenshi233** [comment]
Thank you.
谢谢你。

**Comment by chenshi233** [comment]
Oh, one last thing, you can add this Chinese paragraph to your MOD profile in Thunderstore.

**Comment by chenshi233** [comment]
1.4.0版本已加入中文。
以记事本方式打开“BepInEx/config/WeaponStatShower.cfg”文件
把倒数第二段最后一行的Language = English改为Language = Chinese，即可切换为中文。
祝你游戏愉快

**Comment by Dacrenzio** [comment]
Sure :)

**Comment by chenshi233** [comment]
the last last thing.
![image](https://github.com/Dacrenzio/GTFO-WeaponStatShower/assets/77187872/6b280c17-b94d-4775-baf1-1177827ff78f)

**Comment by chenshi233** [comment]
Maybe,have time to "work together or die together".

**Comment by Dacrenzio** [comment]
that would be cool! why not :D

**Comment by chenshi233** [comment]
sorry,my steam has been hacked,all of my steam friends has been deleted.
